# Store your Google API Key here
GOOGLE_API_KEY = "AIzaSyD4OJgbK_6ibyT1tPl3XFmtt1s7oIoxTZo"

# Store your OpenWeather API Key here
OPENWEATHER_API_KEY = "d67c7a5ae631afb152c40991e9046eb4"

# OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY" # Removed/Commented out
