# Store your Google API key here
GOOGLE_API_KEY = "AIzaSyAmc78NU-vGwvjajje2YBD3LI2uYqub3tE"

# Store your OpenWeather API key here (EXACT name required)
OPENWEATHER_API_KEY = "407c7a5ae631afb352c49931e0946eb4"

# OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY" # Reserved/Commented out
