# Store your Google API key here
GOOGLE_API_KEY = "41289y0403gbK_61by71bP13XFnet1470IoXTZo"

# Store your OpenWeather API key here (EXACT name required)
OPENWEATHER_API_KEY = "407c7a5ae631afb352c49931e0946eb4"

# OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY" # Reserved/Commented out
